name: gps_telemetry
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Arquitetura MVVM - Injeção de Dependência e Roteamento
  flutter_modular: ^6.3.4

  # Gerenciamento de Estado (View)
  provider: ^6.1.2

  # Localização e Velocidade
  geolocator: ^13.0.1

  # Aceleração
  sensors_plus: ^6.0.1

  # Direção (Bússola)
  flutter_compass: ^0.8.0

  # Mapas
  google_maps_flutter: ^2.9.0

  # Banco de Dados Local
  sqflite: ^2.4.1

  # Utilitários adicionais
  permission_handler: ^11.3.1
  path: ^1.9.1
  
  # Requisições HTTP
  http: ^1.2.2
  
  # Exportação de dados
  csv: ^6.0.0
  share_plus: ^10.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

